const menu = [
  {
    id: 1,
    title: 'Fluffy Clouds',
    category: 'breakfast',
    price: 15.99,
    img: '/images/item-1.jpeg',
    desc: `Indulge in a stack of fluffy clouds that magically melt in your mouth, topped with a drizzle of maple syrup and a dollop of whipped cream. Breakfast bliss awaits!`,
  },
  {
    id: 2,
    title: 'The Mighty Two ',
    category: 'lunch',
    price: 13.99,
    img: '/images/item-2.jpeg',
    desc: `Brace yourself for a beefy bonanza! The Mighty Two combines not one, but two juicy patties grilled to perfection, stacked with cheese, fresh veggies, and secret sauce. It's a burger lover's dream come true.`,
  },
  {
    id: 3,
    title: 'Colossal Shake',
    category: 'shakes',
    price: 6.99,
    img: '/images/item-3.jpeg',
    desc: `Prepare for a shake that defies the laws of gravity! The Colossal Shake towers above the rest with layers of creamy goodness, topped with mountains of whipped cream, sprinkles, and a cherry on top. It's a monster-sized treat!`,
  },
  {
    id: 4,
    title: 'Countryside Blis',
    category: 'breakfast',
    price: 20.99,
    img: '/images/item-4.jpeg',
    desc: `ake a trip to the idyllic countryside with this dish. Savour the flavors of farm-fresh eggs, sizzling bacon, golden hash browns, and buttery toast. It's a delightful taste of rustic charm.`,
  },
  {
    id: 5,
    title: 'Egg-plosion',
    category: 'lunch',
    price: 22.99,
    img: '/images/item-5.jpeg',
    desc: `Brace yourself for an egg-plosive experience! The Egg-plosion combines fluffy scrambled eggs, savory sausage, melted cheese, and zesty salsa in a fiesta of flavors. It's an egg-cellent attack on your taste buds!`,
  },
  {
    id: 6,
    title: 'Choco-licious Dream',
    category: 'shakes',
    price: 18.99,
    img: '/images/item-6.jpeg',
    desc: `Enter a world of sweet fantasies with the Choco-licious Dream. Dive into a creamy chocolate milkshake blended with crushed Oreos, crowned with a mountain of whipped cream and a sprinkle of cookie crumbs. It's a dreamy delight!`,
  },
  {
    id: 7,
    title: 'Bacon Bonanza',
    category: 'breakfast',
    price: 8.99,
    img: '/images/item-7.jpeg',
    desc: `Calling all bacon enthusiasts! Brace yourself for a tidal wave of crispy, smoky bacon stacked high on a toasted bun with fresh lettuce, ripe tomatoes, and a tangy sauce. It's a bacon lover's paradise!`,
  },
  {
    id: 8,
    title: 'Stars and Stripes',
    category: 'lunch',
    price: 12.99,
    img: '/images/item-8.jpeg',
    desc: `Experience the taste of freedom with the Stars and Stripes. This classic all-American burger features a juicy patty topped with cheese, crisp lettuce, juicy tomatoes, and tangy pickles. It's a patriotic feast!`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `When times get tough, the Quarantine Companion is there to keep you company. This hearty dish brings together comfort food favorites like mac and cheese, mashed potatoes, and a juicy meatloaf. It's your loyal buddy in culinary isolation!`,
  },
];
export default menu;
